### ISSUE TITLE
Trouble with 4D web server

### ISSUE THREAD

**Issue by olivierfaure** [miyako/4d-plugin-HTMLTOX#1]
Hi,

I use HTMLTOX in a website to create PDF of a page of my website, during the process (± 20s), all web requests are not treated by 4D. All arrives when HTMLTOX finished... A way to avoid this behavior ? it could be 400 waiting sometime...

thx

**Comment by miyako** [comment]
it depends on the platform, I guess, but either way some major refactoring in C is necessary.

on Windows, a more sophisticated use of WaitForSingleObject() might be possible.
on Mac, a more complex, threaded use of NSConnection might be possible.

in any case, the plugin is intentionally synchronous to be a simple call,
the price of which is that the call is blocking. it is a trade off.

perhaps in you case you should not use the command directly on the web server.
