### ISSUE TITLE
Freeze in v17 MacOS

### ISSUE THREAD

**Issue by olivierfaure** [miyako/4d-plugin-HTMLTOX#3]
process constantly freeze with HTML Convert command with v17, it works in v16

**Comment by miyako** [comment]
thanks for flagging the issue. please hang on there, I have a lot to do but hope to update this one soon.

**Comment by miyako** [comment]
I feel like it is time to retire the plugin. 
the library is does not sit very well embedded as a plugin.
moreover, it is not thread safe.

LAUNCH EXTERNAL PROCESS+wkhtmltopdf/wkhtmltoimage should be considered as a replacement.

**Comment by miyako** [comment]
so here is the component edition

https://github.com/miyako/4d-component-wkhtmltopdf
